### ISSUE TITLE
Compile error due to inconsistent prama versions

### ISSUE THREAD

**Issue by jkryanchou** [PatrickAlphaC/erc20-brownie#1]
There was an error raised when I ran `brownie run ./scripts/1_deploy_token.py`, and I have figured it out the reason why it raised the exception.

The `OurToken.sol`' solidity version was inconsistent with `ERC20.sol` of `openzeppelin@3.4.0` solidity version. refer the details below

The `OurToken.sol` solidity version specify 
![image](https://user-images.githubusercontent.com/1206342/147333861-5c0e81b1-e12e-41b4-b31c-62aaf81bf831.png)

While `ERC20.sol` of `openzeppelin@3.4.0` solidity version was

![image](https://user-images.githubusercontent.com/1206342/147333925-5a42b0be-f89f-4251-9971-cadef47a82c3.png)

They were consistent. So when you ran the command as above. There is no suitable version of solidity for compile those files.

**Comment by stackaccount1** [comment]
I am also running into this error, did you solve it @jkryanchou

**Comment by stackaccount1** [comment]
```
dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.4.0
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.0'
```
Changing 3.4.0 to 4.4.0 in the brownie-config worked for me brother.

also have pragma at ^0.8.0, still showing the error but allowed to compile and looks like the token is deploying
